import { Inter } from "next/font/google";
import '../../styles/globals.scss'


export const metadata = {
  title: "DEV APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[500px] w-full mx-auto min-h-screen bg-gradient-to-br from-[#7469B6] via-[#E1AFD1] to-[#FFE6E6]">
        {children}          
        </div>  
      </body>
    </html>
  );
}
